### ISSUE TITLE
Bug: Podcast playback loses progress time

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#105] opened 2022-12-29 16:15 UTC
Stub ticket: When returning to an episode, the podcast often starts at the beginning instead of at the 'last played' point. I haven't found a pattern.

**Comment by jimBeaux27** [comment] 2022-12-30 15:16
@pitoi @tomastiminskas I did some experiments. I notice that when I play subscribed podcasts it saves my place pretty well but when I go to the "recommendations" it seems to exhibit this issue. I also notice the UI seems slightly different. Am I mistaken on that Tom?

**Comment by jimBeaux27** [comment] 2022-12-30 15:27
https://user-images.githubusercontent.com/96802642/210086326-adfe460a-83d8-49ed-a4ca-24c97a1aaced.mov

Video that backs up what @pitoi is saying. I confirmed with Tom that the recommendations player is indeed unique from the PodcastPlayerView. My opinion is that the latter is much more stable and bug free than the former. I think we may want to consider consolidating by just invoking the existing, bug free player for audio recommendations as a way of reducing "surface area" for bugs and keeping technical debt low.

**Comment by tomastiminskas** [comment] 2022-12-30 16:02
@jimBeaux27 I think we are messing up 2 different things:
- On normal podcast player there seems to be an issue where the last played point is missed sometimes and the episode is played from the beginning. That's the issue Paul is reporting and as there is no defined patter to reproduce it, we should try to find it. 
- On recommendations instead, I made the logic so when tapping on an episode to play it, it will always start playing from the clip start time coming on the recommendation json (the one highlighted with the white semitransparent view over the progress slider). That was intentionally and we could change it if @pitoi thinks we should, but it's not actually a bug. 

Regarding the differences between podcast player and recommendations player, as we discussed, that was done that way since it's combined player that can play audio or YouTube videos. So we can't just open the right player depending on the type of the recommendations if we want to allow user to play a different item type once on the player from the list at the bottom.

**Comment by jimBeaux27** [comment] 2022-12-30 16:26
@tomastiminskas ok that makes sense now I understand why recommendations seemed to be broken. It's a feature not a bug.

**Comment by tomastiminskas** [comment] 2022-12-30 16:33
@jimBeaux27 It's good to know they seem broken for you, since you are new to the project and your experience with the app is similar to a user's experience. So it's good you are playing with it and writing down you feedback here. Based on that we can think what's the best way for the recommendations player to work

**Comment by jimBeaux27** [comment] 2023-01-12 15:06
Could this be related to or at least improved by #121 ? I'm thinking there's about three issues that could be resolved by having a better podcast status API/regime

**Closed** 2023-02-09 12:56 UTC
