### ISSUE TITLE
Delete Sphinx Account - UI Addition

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-ios#371] opened 2023-12-14 14:03 UTC
Add prominent red button "Delete Account" On the very bottom of Profile > Advance Page.

**Comment by Antanasijevic** [comment] 2023-12-15 12:02
@tomastiminskas Here is an option for "Delete Account" button

Figma project
https://www.figma.com/file/L1oq8hh8kYU90bQxPAin3G/Mobile-Design-System---Dark-Version?type=design&node-id=7433%3A9148&mode=design&t=UZIe0vqWRPpF2q9j-1

![image](https://github.com/stakwork/sphinx-ios/assets/13258550/5c2a4d46-b314-4c5f-bb7f-9f0ebe4f9d5c)

**Comment by tomastiminskas** [comment] 2024-04-11 14:00
Closing this since it was designed for Android since we were asked to add this feature to be approved on Google Play Store

**Closed by tomastiminskas** 2024-04-11 14:00 UTC
